# Generated by Django 4.2.23 on 2025-08-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastinnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faerslunumer', models.TextField(blank=True, db_column='FAERSLUNUMER', null=True)),
                ('emnr', models.TextField(blank=True, db_column='EMNR', null=True)),
                ('skjalanumer', models.TextField(blank=True, db_column='SKJALANUMER', null=True)),
                ('fastnum', models.TextField(blank=True, db_column='FASTNUM', null=True)),
                ('heimilisfang', models.TextField(blank=True, db_column='HEIMILISFANG', null=True)),
                ('postnr', models.TextField(blank=True, db_column='POSTNR', null=True)),
                ('heinum', models.TextField(blank=True, db_column='HEINUM', null=True)),
                ('svfn', models.TextField(blank=True, db_column='SVFN', null=True)),
                ('sveitarfelag', models.TextField(blank=True, db_column='SVEITARFELAG', null=True)),
                ('utgdag', models.TextField(blank=True, db_column='UTGDAG', null=True)),
                ('thinglystdags', models.TextField(blank=True, db_column='THINGLYSTDAGS', null=True)),
                ('kaupverd', models.TextField(blank=True, db_column='KAUPVERD', null=True)),
                ('fasteignamat', models.TextField(blank=True, db_column='FASTEIGNAMAT', null=True)),
                ('fasteignamat_gildandi', models.TextField(blank=True, db_column='FASTEIGNAMAT_GILDANDI', null=True)),
                ('fyrirhugad_fasteignamat', models.TextField(blank=True, db_column='FYRIRHUGAD_FASTEIGNAMAT', null=True)),
                ('brunabotamat_gildandi', models.TextField(blank=True, db_column='BRUNABOTAMAT_GILDANDI', null=True)),
                ('byggar', models.TextField(blank=True, db_column='BYGGAR', null=True)),
                ('fepilog', models.TextField(blank=True, db_column='FEPILOG', null=True)),
                ('einflm', models.TextField(blank=True, db_column='EINFLM', null=True)),
                ('lod_flm', models.TextField(blank=True, db_column='LOD_FLM', null=True)),
                ('lod_flmein', models.TextField(blank=True, db_column='LOD_FLMEIN', null=True)),
                ('fjherb', models.TextField(blank=True, db_column='FJHERB', null=True)),
                ('tegund', models.TextField(blank=True, db_column='TEGUND', null=True)),
                ('fullbuid', models.TextField(blank=True, db_column='FULLBUID', null=True)),
                ('onothaefur_samningur', models.TextField(blank=True, db_column='ONOTHAEFUR_SAMNINGUR', null=True)),
                ('date', models.TextField(blank=True, db_column='date', null=True)),
            ],
            options={
                'db_table': 'fastinn_data',
                'managed': False,
            },
        ),
    ]
