# Generated by Django 4.2.23 on 2025-08-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastinn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastinndata',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
