# Generated by Django 4.2.23 on 2025-08-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastinn_app', '0002_alter_fastinndata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastinndata',
            options={'managed': False},
        ),
    ]
